// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kergtzqubiljygamkqtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtlcmd0enF1YmlsanlnYW1rcXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzIwNTksImV4cCI6MjA2NTUwODA1OX0.bF0bA6jpgQF4yOrZm4zpnb9ngZLfGd_zEgW6Q5WRwY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);